name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &
        env:
          CYPRESS_BASE_URL: http://localhost:5173 

      - name: Run Cypress tests
        run: npx cypress run

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: cypress/videos
