name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'  # Your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: echo "VITE_SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
        run: echo "VITE_SUPABASE_KEY=$SUPABASE_KEY" >> $GITHUB_ENV
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Start server
        run: npm run dev &
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run Cypress tests
        run: npx cypress run

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: cypress/videos
